export { dictEntries } from './lib/dictionary-helpers/dict-entries';
export { dictFromEntries } from './lib/dictionary-helpers/dict-from-entries';
export { dictKeys } from './lib/dictionary-helpers/dict-keys';
export { boxedLog } from './lib/shell-script-utilities/boxed-log';
export { exec } from './lib/shell-script-utilities/exec';
export { workspaceRoot } from './lib/shell-script-utilities/workspace-root';
export { isBigInt } from './lib/type-safe-functions/is-big-int';
export { isBoolean } from './lib/type-safe-functions/is-boolean';
export { isDate } from './lib/type-safe-functions/is-date';
export { isError } from './lib/type-safe-functions/is-error';
export { isFunction } from './lib/type-safe-functions/is-function';
export { isNull } from './lib/type-safe-functions/is-null';
export { isNumber } from './lib/type-safe-functions/is-number';
export { isRegExp } from './lib/type-safe-functions/is-reg-exp';
export { isString } from './lib/type-safe-functions/is-string';
export { isSymbol } from './lib/type-safe-functions/is-symbol';
export { isTypesKeys, isType } from './lib/type-safe-functions/is-type';
export { isUndefined } from './lib/type-safe-functions/is-undefined';
export { notNil } from './lib/type-safe-functions/not-nil';
export type { KeyOf } from './lib/dictionary-helpers/key-of.d';
export type { NestedObjectKeys } from './lib/dictionary-helpers/nested-object-keys.d';
export type { ExecResult, ExecOptions } from './lib/shell-script-utilities/exec';
export type { UnknownFunction } from './lib/type-safe-functions/is-function';
export type { IsTypeKey, IsTypeKeyType } from './lib/type-safe-functions/is-type';
export type { IsTypes } from './lib/type-safe-functions/is-types.d';
